spring:
  datasource:
    url: jdbc:h2:file:C:/Users/glyze/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE # in-memory database
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update                 # creates/updates tables automatically
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true                     # enable H2 console
      path: /h2-console                 # URL path for console

# Optional: show SQL queries in the console
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
