spring:
  application:
    name: keycloak1

  security:
    oauth2:
      client:
        registration:
          oauth2-authorization-code-flow:
            client-id: oauth2-authorization-code-flow
            client-secret: ${CLIENT_SECRET}
            scope: openid, profile, email, roles
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8081/login/oauth2/code/oauth2-authorization-code-flow"
        provider:
          oauth2-authorization-code-flow:
            issuer-uri: "http://127.0.0.1:8080/realms/oauth2-demo"

server:
  port: 8081