spring:
  application:
    name: ai_security_playground
  security:
    user:
      name: testuser
      password: testpass
      roles: USER

logging:
  level:
    org.springframework.security: TRACE

